# Services

services:
  # Apache + PHP
  apache_php_phpini:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'apache_php_v2'
    volumes:
      - ./src/:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 80
    ports:
      - '8080:80'

# Lanzar con
# docker-compose up -d

# Ver los logs con
# docker-compose logs -f
